### ISSUE TITLE
error creating density map

### ISSUE THREAD

**Issue by darissa** [dmburd/S-DCNet#1]
Hi,
Thanks for sharing this code. I got the following error while running the command: python gen_density_maps.py dataset=ShanghaiTech_part_B

one_head_gaus_subset / np.sum(one_head_gaussian) ValueError: operands could not be broadcast together with shapes (42,847) (42,0) (42,847).

the environment:
python : 3.6.10
pytorch : 1.3.1
torchvision : 0.4.2
numpy : 1.18.4

**Comment by dmburd** [comment]
Hello!
Thanks for reporting the issue. Let's try to debug this. Please checkout the commit 8fd7809. The exception was thrown during the evaluation of
```
           dmap[up:down, left:right] += \
                one_head_gaus_subset / np.sum(one_head_gaussian)
```
(lines 219-220 of `gen_density_maps.py`). 
Wrap the expression above into a try/except block with the following contents:
```
            try:
                dmap[up:down, left:right] += \
                    one_head_gaus_subset / np.sum(one_head_gaussian)
            except:
                types_ = (str, int, dict, np.float64, np.ndarray)
                loc = {k: v for k, v in locals().items() if isinstance(v, types_)}
                np.savez("loc.npz", **loc)
                e()
```
Please send me the generated file `loc.npz`.

**Comment by darissa** [comment]
Did you able to download the file? Since this is my first time upload file here.

[loc.zip](https://github.com/dmburd/S-DCNet/files/4692356/loc.zip)

**Comment by dmburd** [comment]
Yes, I have downloaded the file. The debugging info indicates that there are invalid entries in the head points annotations (at least for "ShanghaiTech/part_B/test_data/images/IMG_312.jpg").
What was the link that you used to download the dataset?

**Comment by darissa** [comment]
I get the dataset from the following link

https://www.kaggle.com/tthien/shanghaitech-with-people-density-map

**Comment by darissa** [comment]
Is it due to dataset? I can't open the dropbox link. 

Thank you for assisting me.

**Comment by dmburd** [comment]
The dropbox link is dead, that's true.
Try a different dataset from kaggle: https://www.kaggle.com/tthien/shanghaitech
I have no issues with that one.

**Comment by darissa** [comment]
Yes, successfully run the line without error using the given dataset. However, when running the command line : 

python gen_density_maps.py \
    dataset=ShanghaiTech_part_B \
    dataset.xhp_gt_dmaps_dir=./Test_Data/SH_partB_Density_map/test/gtdens

I got the following error:

    ret.return_value = task_function(task_cfg)
  File "gen_density_maps.py", line 414, in main
    xhp_dmaps_dict = xhp_density_maps(cfg.dataset.xhp_gt_dmaps_dir)
  File "gen_density_maps.py", line 308, in xhp_density_maps
    bname2dmap_dict[bn] = mat['density_map']
KeyError: 'density_map'

Suspected due to dataset. I download the Test Data from : 
https://drive.google.com/file/d/1q7ESNoB8cYJTANEuiNlVf8toPSfI81m7/view

Thanks again

**Comment by darissa** [comment]
I have checked the path, it is correct where I saved the gtdens .mat file.

**Comment by dmburd** [comment]
What is the version of `scipy` in your environment?

**Comment by darissa** [comment]
scipy - 1.4.1

**Comment by darissa** [comment]
# Name                    Version                   Build  Channel
blas                      1.0                         mkl
certifi                   2020.4.5.1               py36_0
cffi                       1.14.0                    py36h7a1dbc1_0
cudatoolkit               10.1.243             h74a9793_0
cycler                    0.10.0                   pypi_0    pypi
decorator                 4.4.2                    pypi_0    pypi
easydict                  1.9                      pypi_0    pypi
freetype                  2.9.1                ha9979f8_1
hydra-core                0.11.3                   pypi_0    pypi
icc_rt                         2019.0.0             h0cc432a_1
imageio                   2.8.0                    pypi_0    pypi
intel-openmp          2020.1                      216
joblib                       0.15.1                   pypi_0    pypi
jpeg                      9b                   hb83a4c4_2
kiwisolver                1.2.0                    pypi_0    pypi
libpng                    1.6.37               h2a8f88b_0
libtiff                        4.1.0                h56a325e_0
matplotlib                3.1.2                    pypi_0    pypi
mkl                       2020.1                      216
mkl-service               2.3.0            py36hb782905_0
mkl_fft                      1.0.15           py36h14836fe_0
mkl_random            1.1.1            py36h47e9c7a_0
networkx                  2.4                      pypi_0    pypi
ninja                     1.9.0            py36h74a9793_0
numpy                     1.18.4                   pypi_0    pypi
numpy-base             1.18.1           py36hc3f5095_1
olefile                       0.46                     py36_0
omegaconf             1.4.1                    pypi_0    pypi
pandas                    1.0.3                    pypi_0    pypi
pillow                    7.1.2            py36hcc1f983_0
pip                       20.0.2                   py36_3
protobuf                  3.12.2                   pypi_0    pypi
pycparser                 2.20                       py_0
pyparsing                 2.4.7                    pypi_0    pypi
python                    3.6.10               h9f7ef89_2
python-dateutil       2.8.1                    pypi_0    pypi
pytorch                   1.3.1           py3.6_cuda101_cudnn7_0    pytorch
pytz                      2020.1                   pypi_0    pypi
pywavelets                1.1.1                    pypi_0    pypi
pyyaml                    5.3.1                    pypi_0    pypi
q                         2.6                      pypi_0    pypi
scikit-image              0.17.2                   pypi_0    pypi
scikit-learn              0.23.1                   pypi_0    pypi
scipy                     1.4.1                    pypi_0    pypi
setuptools                46.4.0                   py36_0
six                       1.15.0                   pypi_0    pypi
sklearn                   0.0                      pypi_0    pypi
sqlite                    3.31.1               h2a8f88b_1
tensorboardx              2.0                      pypi_0    pypi
threadpoolctl             2.0.0                    pypi_0    pypi
tifffile                  2020.5.25                pypi_0    pypi
tk                        8.6.8                hfa6e2cd_0
torchsummary              1.5.1                    pypi_0    pypi
torchvision               0.4.2                py36_cu101    pytorch
tqdm                      4.41.1                   pypi_0    pypi
vc                        14.1                 h0510ff6_4
vs2015_runtime            14.16.27012          hf0eaf9b_2
wheel                     0.34.2                   py36_0
wincertstore              0.2              py36h7fe50ca_0
xz                        5.2.5                h62dcd97_0
zlib                      1.2.11               h62dcd97_4
zstd                      1.3.7                h508b16e_0

**Comment by darissa** [comment]
i'm sorry, just copy paste from the environment.

**Comment by dmburd** [comment]
You have mentioned a line like
```
ret.return_value = task_function(task_cfg)
```
I don't understand what it means (and where it came from). Could you please copy-paste the whole traceback (printed when the error occurs)?

**Comment by darissa** [comment]
This is the traceback attached. Thank you thank you.

[traceback.txt](https://github.com/dmburd/S-DCNet/files/4700746/traceback.txt)

**Comment by dmburd** [comment]
Let's debug again. Wrap the line `bname2dmap_dict[bn] = mat['density_map']` into a try/except block:
```
        try:
            bname2dmap_dict[bn] = mat['density_map']
        except:
            import pickle
            types_ = (str, int, dict, np.float64, np.ndarray)
            loc = {k: v for k, v in locals().items() if isinstance(v, types_)}
            with open('locals.pickle', 'wb') as f:
                pickle.dump(loc, f, pickle.DEFAULT_PROTOCOL)
            e()
```
and send me the generated file `locals.pickle`.

**Comment by darissa** [comment]
Ok. let's do it.


[locals.zip](https://github.com/dmburd/S-DCNet/files/4701527/locals.zip)

**Comment by dmburd** [comment]
Could you send me your file `S-DCNet/Test_Data/SH_partB_Density_map/test/gtdens/IMG_1.mat`?

**Comment by darissa** [comment]
As attached.

[IMG_1.zip](https://github.com/dmburd/S-DCNet/files/4701815/IMG_1.zip)

**Comment by dmburd** [comment]
Your file is essentially empty. Its size is 180B (should be about 112KB). Seems that your `Test_Data` archive is corrupt. Try downloading it again (https://drive.google.com/open?id=1q7ESNoB8cYJTANEuiNlVf8toPSfI81m7). The archive size is about 298MB.

**Comment by darissa** [comment]
oh, i see. Ok will do it now.

**Comment by darissa** [comment]
Now it can generate cmp folder, however other error appear as attached.

Thank you.

[traceback1.txt](https://github.com/dmburd/S-DCNet/files/4702214/traceback1.txt)

**Comment by dmburd** [comment]
Discard your changes to the source files, checkout the commit f6e39c7 and try again.

**Comment by darissa** [comment]
Thank you thank you. Thank you so much. Now able to create cmp folder. Now start training. Hope everything runs smoothly.

**Comment by darissa** [comment]
Now got error while training. But I think I should close this topic and open the new one right. Thankss
