### ISSUE TITLE
RuntimeError: GPU out of memory

### ISSUE THREAD

**Issue by darissa** [dmburd/S-DCNet#3]
Hi, I'm running inference.py using your trained checkpoints (due to tight schedule for demo) based on our local camera. However, I got runtimeError: Gpu out of memory. I will share my code with you. Thanks a lot for giving your time.

[inference_wana.zip](https://github.com/dmburd/S-DCNet/files/4721034/inference_wana.zip)

**Comment by darissa** [comment]
I debug using spyder, the error start somewhere here:

> c:\users\bolt\s-dcnet\inference_wana.py(156)<module>()
    154 
    155 
2-> 156 @hydra.main(config_path="conf/config_train_val_test.yaml")
    157 def main(cfg):
3   158     orig_cwd = hydra.utils.get_original_cwd()

--Call--
KeyError: '_dh'
--Return--
KeyError: '_dh

**Comment by dmburd** [comment]
What are your hardware resources?

**Comment by darissa** [comment]
I am using GeForce RTX 2070.

**Comment by dmburd** [comment]
I cannot debug everything in your code / setting.
Try launching my script `inference.py` for standalone image files according to the instructions in the readme. First on a Linux machine (if possible), then on Windows. If you encounter crashes likely caused by bugs in my code, please let me know.

**Comment by darissa** [comment]
yeah right. Btw i'm able run your original transcript using some images from test data, it can generate the results, on WIndows. Thanks a lot. Might be due to extraction from video to images. sorry for taking your time, I am a newbie in this field.  Thank you thank you.
