### ISSUE TITLE
SSDCNet or SDCNet

### ISSUE THREAD

**Issue by darissa** [dmburd/S-DCNet#5]
Hi,

I've successfully run your code last time. However, I have a question, this code is applying SDCNet right? How about SSDCNet? Do you include the model in this code github?

Thank you.

**Comment by darissa** [comment]
I think I got it where to change from SDCNet to SSDCNet.

**Comment by dmburd** [comment]
Yes, the option `model.supervised` is set to `true` by default (SS-DCNet is used). Specify `false` in order to use S-DCNet.
